version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user_template
      POSTGRES_PASSWORD: password_template
      POSTGRES_DB: db_template
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
