# Generated by Django 4.1.7 on 2023-03-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DieselFuelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_price', models.FloatField(blank=True)),
                ('df_taneko_price', models.FloatField(blank=True)),
                ('df_winter_price', models.FloatField(blank=True)),
                ('df_arctica_price', models.FloatField(blank=True)),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gasstation')),
            ],
        ),
    ]
